###
GET http://localhost:8080/clothing/all

###
GET http://localhost:8080/clothing?tags=tag1,tag2

###
POST http://localhost:8080/clothing
Content-Type: application/json

{
  "name": "test",
  "imageSrc": "fghffgghgjlhjh",
  "tags": [
    "tag1",
    "tag2",
    "tag3"
  ]
}

###
@id = 6708136f12abd94332291a34
PATCH http://localhost:8080/clothing/{{id}}
Content-Type: application/json

{
  "name": "test2"
}